### ISSUE TITLE
Core Data and Caching  

### ISSUE THREAD

**Issue by yungobiwan** [shoutem/react-native-shopify#17]
I've been trying to renew a customer account token every time the app is active as advised in the shopify Docs

`  RCT_EXPORT_METHOD(renewCustomerToken: (RCTPromiseResolveBlock)resolve rejecter:(RCTPromiseRejectBlock)reject)
  {
    [self.client renewCustomerTokenCallback:^(BUYCustomerToken *token, NSError *error) {
    if (token && !error) {
          resolve (token);
    }
    else {
      return reject([NSString stringWithFormat: @"%lu", (long)error.code], error.localizedDescription, error);
    }
}];
}`

The actual code that gets executed in BUYClient+Customer .m  

`- (NSOperation *)renewCustomerTokenCallback:(BUYDataTokenBlock)block
{
	if (self.customerToken) {
		NSURL *url = [self urlForCustomersTokenRenewal];

		return [self putRequestForURL:url object:nil completionHandler:^(NSDictionary *json, NSHTTPURLResponse *response, NSError *error) {
			BUYCustomerToken *customerToken = nil;
			if (json && !error) {
				customerToken = [BUYCustomerToken customerTokenWithJSONDictionary:json];
			}
			block(customerToken, error);
		}];
	}
	else {
		block(nil, [NSError errorWithDomain:BUYShopifyErrorDomain code:BUYShopifyError_InvalidCustomerToken userInfo:nil]);
		return nil;
	}`

It appears self.customerToken is not set so I get the error message however, when i log in using loginCustomerWithCredentials, self.customerToken is set when createTokenForCustomerWithCredentials is called

`			self.customerToken = [BUYCustomerToken customerTokenWithJSONDictionary:json];
`

Can you help to figure out how to have customerToken persist across app launches. How are you guys keeping cart across app launches as well?

**Comment by Air-Miha** [comment]
@yungobiwan 

Store in permanent storage. Since RNs AsyncStorage is not secure, use this library:

https://github.com/oblador/react-native-keychain

See this topic for more info:

http://stackoverflow.com/questions/39148714/is-react-natives-async-storage-secure

Then, when the app loads, just fetch the token and renew it. 

Does this work for you?

**Comment by yungobiwan** [comment]
I will not be able able to call  - (NSOperation *)renewCustomerTokenCallback:(BUYDataTokenBlock)block because it relies on self.customerToken. Even if I were to store it in keychain i will not be able to renew the token by invoking the function above

Is there any way to use core data? how are you storing cart from app launches

**Comment by Air-Miha** [comment]
We use AsyncStorage for the cart. But, a customer token needs to be saved in a secure place.

When you fetch the token from secure storage, set it on the BuyClient. You have an instance available in _RNShopify.m_. Expose a method _setCustomerToken_, call it from JavaScript, and do something like this:

`self.client.customerToken = customerToken`

Then you can renew it. Check out this test file for an example:

https://github.com/Shopify/mobile-buy-sdk-ios/blob/ee3bc3b5dd8f53e93c055e183470bc7849c8e9ac/Mobile%20Buy%20SDK/Mobile%20Buy%20SDK%20Tests/BUYClientTest.m

**Comment by Air-Miha** [comment]
Btw, if you want to store cart data, use AsyncStorage.

**Comment by yungobiwan** [comment]
Ah okay, set in secure storage after login and then when app launches set self.client.customerToken 
and then renew. Don't know why I didn't think about that.

Thanks Sir!

**Comment by Air-Miha** [comment]
@yungobiwan, 

Do you have the entire customer API working? If so, we'd very much appreciate your contribution to the bridge! Btw, I've updated the documentation. You can see in the only Pull Request. Let me know if you have any suggestions.

**Comment by yungobiwan** [comment]
@Air-Miha I haven't fully implemented the customer API but once one I do i'll submit a pull request.
