### ISSUE TITLE
Initialize error

### ISSUE THREAD

**Issue by mikecobas** [shoutem/react-native-shopify#20]
<img width="283" alt="screen shot 2017-04-18 at 16 50 56" src="https://cloud.githubusercontent.com/assets/1024890/25154697/5193541c-2457-11e7-8e29-1927ea50dfc2.png">

Any idea how can i fix it?

**Comment by Air-Miha** [comment]
Hi @mikecobas,

Did you run react-native link? What was the output?

**Comment by adamjacob** [comment]
I'm having the same issue, I'm getting this...

`.../node_modules/react-native-shopify/ios/RNShopify.h:10:9: 'Buy.h' file not found`

Any ideas?  I reinstalled and did the instructions for the manual install as well.

**Comment by adamjacob** [comment]
Never mind totally my fault, I didn't have the Shopify Mobile Buy SDK installed right.  All good now 👍

**Comment by Vladimir-Vdovic** [comment]
Closing since it's resolved.
