### ISSUE TITLE
Buy.h is undefined

### ISSUE THREAD

**Issue by jgrancher** [shoutem/react-native-shopify#5]
Hi! I just wanted to raise that when I try linking your module, the build fail because `RNShopify.h` is looking for importing the SDK file `Buy.h` that doesn't exist anywhere.

Also, in that file, I think there's a typo:
```objectivec
#import "<React/RCTBridgeModule.h>"
```
should be:
```objectivec
#import <React/RCTBridgeModule.h>
```

**Comment by sirhotsauce** [comment]
Hey Jérémy,

Thanks for reporting this! We're using the bridge with React Native 0.39 so I didn't notice the typo. I'll fix this. 

Regarding the `Buy.h` file, did you include the `Mobile Buy SDK` in your project? Put the dependency in your Pod file and install it. The bridge will look for the headers in your `Pods` folder.
Could you try this and tell me if it works?

**Comment by jgrancher** [comment]
Hi @sirhotsauce,
Thanks for your help :) Indeed, it worked like a charm!

So, for the record, I had to:
- `npm i -S react-native-shopify@0.2.1`
- Create a Podfile in `MyProject/ios/Podfile`
- Write
```bash
target 'MyProject'
pod 'Mobile-Buy-SDK'
```
in it, as per [your link to their doc](https://github.com/Shopify/mobile-buy-sdk-ios#cocoapods).

Sorry about that, I just misread the docs... Stayed up too late I reckon! Perhaps it might be worthwhile to add the link [in this section](https://github.com/shoutem/react-native-shopify#including-mobile-buy-sdk) though?

I'll play around with the API now. Thanks again :)
