### ISSUE TITLE
Documentation for creating checkout and setting shipping address

### ISSUE THREAD

**Issue by yungobiwan** [shoutem/react-native-shopify#6]
Hello! I'm having issues creating a checkout or setting an address

After I invoke the method 

`  return Shopify.checkout([{ quantity: 1,variant: 22912315077 }]);`

I get the error 

`Exception '-[__NSCFNumber count]: unrecognized selector sent to instance 0xb00000555ae2ec53' was thrown while invoking checkout on target RNShopify with params (
        (
                {
            quantity = 1;
            variant = 22912315077;
        }
    ),
    2,
    3
)`

What is the right way to call checkout, setCustomerInformation and complete checkout. Can the documentation be updated with an example. I am able to get the product object calling Shopify.getProductsPage() but having issues with the other methods

**Comment by sirhotsauce** [comment]
Hey jungobiwan!

For checkout, you need to use the variant object that you got from Shopify when fetching products. Like this: 
`Shopify.getProducts(1)
    .then((products) => {
       const cart = [{quantity: 1, variant: products[0].variants[0]}];
      Shopify.checkout(_.cloneDeep(cart)).then(() => {
         // Set customer information
      });
    });`

You're currently using IDs? 

As for customer information, you need an object with fields mentioned in the official documentation (it's the same for both iOS and Android): 

https://help.shopify.com/api/sdks/custom-storefront/mobile-buy-sdk/ios/integration-guide/checkout#native-checkout

Look under: _Specifying Billing and Shipping Addresses_

Here is an example:

`
const addressInformation = {
  firstName: 'First name',
  lastName: 'Last name',
  address1: 'Address',
  city: 'City',
  zip: '10000',
  countryCode: 'US',
}; 
Shopify.setCustomerInformation(customer@somerandommail.com, addressInformation).then(() => { });
`

I'll update the documentation with detailed examples for all methods but I hope that this will help you in the meantime!

**Comment by yungobiwan** [comment]
Yes I was using the variant id. I have updated my code but I getting ' cannot read property 'title' of undefined' using 

`    Shopify.getProductsPage(1).then(products => {
     return products}).then(products => {
    return Shopify.checkout([{ quantity: 1,variant: products[0].variants[0] }]);
  }).then(res => {
      ...
})
`

**Comment by sirhotsauce** [comment]
I forgot to mention that you also need to include the product to which the variant belongs. We use it to give you a user-friendly error message in case the checkout fails (see _index.js_ for details). Just include the product, like this:

`Shopify.getProducts(1)
    .then((products) => {
       const cart = [{item: products[0], quantity: 1, variant: products[0].variants[0]}];
      Shopify.checkout(_.cloneDeep(cart)).then(() => {
         // Set customer information
      });
    });`

Note that the key for a product in the cart is _item_. A cart is an array of _item_ (product), _variant_ and _quantity_.

We're using this bridge in a real app but the documentation is currently lagging and we'll fix that asap!

**Comment by yungobiwan** [comment]
Okay thats seemed to do the trick. Last issue I'm facing is with finalizing the checkout

`  const card = {number:1234567891011,expiryMonth:11,expiryYear:20,cvv:782,firstName:'Yung',lastName:'Obiwan'}
    return Shopify.completeCheckout(card);`

I'm getting the error 

`Exception '-[__NSCFNumber buy_trim]: unrecognized selector sent to instance 0xb1345439b9841403' was thrown while invoking completeCheckout on target RNShopify with params (
        {
        cvv = 782;
        expiryMonth = 11;
        expiryYear = 20;
        firstName = Yung;
        lastName = Obiwan;
        number = 1234567891011;
    },
    4,
    5
)`

**Comment by yungobiwan** [comment]
I was able to get it to work. Works like a charm!

**Comment by sirhotsauce** [comment]
Awesome! So, you are able to perform the checkout to completion?

**Comment by yungobiwan** [comment]
Yes I was able to complete the checkout. Works perfectly. Let me know if you need any help with the documentation.


Thanks again.

**Comment by webmaster100** [comment]
@Air-Miha
I tried to create checkout like this:

    ` var product = {"published_at":"2017-04-02T23:20:09+0000",
            "options":[{"product_id":8391086155,"id":10051740747,"name":"Title","position":1}],
            "minimum_price":"1",
            "handle":"product-with-variant",
            "tags":"NEW, Toddler",
            "minimum_compare_at_price":"2",
            "created_at":"2017-04-02T23:20:09+0000",
            "title":"Product with variant",
            "body_html":"new body",
            "variants":[{"taxable":false,"position":1,"id":28759350219,
                "price":"1","requires_shipping":true,
                "title":"Default Title","sku":"","grams":"0","available":true,
                "options":[{"value":"Default Title","option_id":10051740747,"name":"Title"}],
                "compare_at_price":"2"}],
            "product_type":"","images":[{"variant_ids":[],
                "product_id":8391086155,"position":1,"id":17355651723,
                "src":"https://cdn.shopify.com/s/files/1/1626/9455/products/fish_toy.jpg?v=1491386756",
                "created_at":"2017-04-05T10:05:56+0000","updated_at":"2017-04-05T10:05:56+0000"}]}

        const cart = [{item: product, quantity: 1, variant: product.variants[0].id}];
         Shopify.checkout(cart).then(checkout => {
            console.log('checkout', checkout);
        }).catch(error => {
            console.log('error', error);
        });`
But got the following error:
'-[__NSCFNumber count]: unrecognized selector sent to instance 0xb000006b230dbcb3' was thrown while invoking checkout on target RNShopify with params (
                {
            item =             {
                "body_html" = "new body";
                "created_at" = "2017-04-02T23:20:09+0000";
             etc ...
I found that the error occurs after the following line
![checkouterror1](https://cloud.githubusercontent.com/assets/10449011/24702662/79ba840a-1a08-11e7-8454-31e966898c43.png)
Can you suggest why this error occurs?

**Comment by webmaster100** [comment]
@Air-Miha 
I am using the following code to create a checkout
` const cart = [{item: products[0], quantity: 1, variant: products[0].variants[0]}];
             Shopify.checkout(cart).then(checkout => {
               console.log('checkout', checkout);
             }).catch(error => {
                console.log('error', error);
             });`
In then, checkout variable is 'true'.  How can I access the created checkout? I suppose I need token or some ID of this checkout.
The next step will be to display and complete the checkout, but I did not found how I can do this in the mobile app (not website) using the created checkout? Could you provide or give a link to a sample code to display and complete the checkout
Thank you!

**Comment by webmaster100** [comment]
@Air-Miha 
I am using the following code to create a checkout
`  Shopify.checkout(cart).then(checkout => {
                    Shopify.setCustomerInformation('test@gmail.com', addressInformation).then(() => {`
As I see the checkout is created  RNShopify.m.
The next step will be to display and complete the checkout, but I did not found how I can do this in the mobile app (not inside webview or browser) using the created checkout? Could you provide or give a link to a sample code to display and complete the checkout
Thank you!

**Comment by Air-Miha** [comment]
@webmaster100 

You'll need your own UI form to capture user information. Then you just need to update the checkout. Check how we did it in our Shopify app:

https://github.com/shoutem/extensions

Go to shoutem-shopify and study the screens. These screens dispatch checkout actions. The _actionCreators.js_ file call the Shopify API.

Now you reminded me that I need to update the documentation here, with all of the methods.

**Comment by Air-Miha** [comment]
@webmaster100,

I've updated the documentation and sent a PR. I included images and code examples for each checkout step, with some helpful links. Let me know what you think and if you need anything more!

**Comment by webmaster100** [comment]
@Air-Miha,
Thank you! Have nothing to add. The documentation is clear and images are helpful to understand the checkout flow.

**Comment by austincline09** [comment]
@Air-Miha I get an error message saying "There was an unknown error. Please contact our customer support" every time I try to checkout. Which I'm assuming means it's failing on Shopify's end because the docs say there should be a specific error message telling me what's going wrong. But I have a feeling customer support probably won't be able to help me.

Are there any specific permissions I might need to set in shopify admin or anything in order to checkout? I can load my products and collections and everything but I get that same unknown error when attempting a checkout. 

I'm curious if the checkout method throws an error every time if all of the steps (setCustomerInformation, getShippingRates, etc) are not completed? My cart and addressInformation log out correctly, and if they weren't correct would the error message tell me that? Or tell me I'm missing shipping info instead of the unknown error?

**Comment by Deevent** [comment]
@austincline09 I'm currently facing the same issue than you. Did you find a solution ?

**Comment by sdadrianalvarez** [comment]
@yungobiwan 
I'm getting an empty array too, on 
`Shopify.getShippingRates()`

How did you solve it?

**Comment by amie-wilt** [comment]
@austincline09 @Deevent I'm running into the same issue: "There was an unknown error. Please contact our customer support" every time I try to checkout.

Were you guys able to get around this? Thanks ahead of time.
